### ISSUE TITLE
Cant install sympy based modules.

### ISSUE THREAD

**Issue by AaronSpieler** [Happy-Algorithms-League/e2l-cgp-snn#1]
Hello,

I have tried to build a container with the instructions from your `README`, however, in the end, for the `sympy` based modules I get an error, for which I don't really see the cause (the nest installation seems to have a few issues, but I wasn't able to fix that either, but it doesn't hinder loading the non `sympy` related modules):

- The `Dockerfile`I wrote:
[Dockerfile.txt](https://github.com/Happy-Algorithms-League/e2l-cgp-snn/files/6259948/Dockerfile.txt)

- My `test.py`:
```
import nest
import sympy

print('Installing things:')

nest.Install('usrl_synapse_module')
nest.Install('HomeostaticSTDPmodule')
nest.Install('stdp_sympy_synapse_module') 
nest.Install('us_sympy_synapse_module') 
```

- The trackback I get: 
```
[INFO] [2021.4.5 18:39:43 /~/nest-simulator/nestkernel/rng_manager.cpp:208 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2021.4.5 18:39:43 /~/nest-simulator/nestkernel/rng_manager.cpp:251 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: HEAD@27dc242f1
 Built: Apr  2 2021 22:47:36

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

Installing things:

Apr 05 18:39:44 Install [Info]: 
    loaded module USRL Synapse Module

Apr 05 18:39:44 Install [Info]: 
    loaded module Homeostatic STDP Module
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    nest.Install('stdp_sympy_synapse_module') 
  File "/usr/local/lib/python3.6/site-packages/nest/ll_api.py", line 247, in stack_checker_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nest/lib/hl_api_simulation.py", line 269, in Install
    return sr("(%s) Install" % module_name)
  File "/usr/local/lib/python3.6/site-packages/nest/ll_api.py", line 133, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.lib.hl_api_exceptions.DynamicModuleManagementError: ("DynamicModuleManagementError in Install: Module 'stdp_sympy_synapse_module' could not be opened.\nThe dynamic loader returned the following error: 'file not found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!", 'DynamicModuleManagementError', 'Install', ": Module 'stdp_sympy_synapse_module' could not be opened.\nThe dynamic loader returned the following error: 'file not found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!")

Apr 05 18:39:44 ModelManager::clear_models_ [Info]: 
    Models will be cleared and parameters reset.
```

- When I check the  `LD_LIBRARY_PATH` using the `env` command::
`LD_LIBRARY_PATH=/usr/local/include:/usr/local/lib:/usr/local:/usr/local/lib/nest`

I also ran into problems with a different base image (Ubuntu 20.04), and different `symengine` versions (I checked out the last three major versions.)
It would be very helpful to know which versions of `symengine` you used, as well as whether you have the same errors when running `make installcheck` in your NEST install.
Any help would be greatly appreciated, best case would be of course a working docker image.

Many thanks!
Aaron

**Comment by mschmidt87** [comment]
Hi, reading your description, my first thought is that the `LD_LIBRARY_PATH` is lacking the paths to the symengine installation. For instance, in my case I installed symengine into `~/opt/symengine/ins/lib` and added to the `LD_LIBRARY_PATH`. Are you sure that one of the paths in your `LD_LIBRARY_PATH` contains the symengine installation?

**Comment by AaronSpieler** [comment]
I install the `symengine` based modules as described with `-Dwith-symengine=/usr/local` (if I change it to something else it complains that it can't find the install), since I installed `symengine` in `/usr/local`, which is part of my `LD_LIBRARY_PATH`. 
So as far as I know it should be the right path, and it should work, but it doesn't, so something is not right.

**Comment by mschmidt87** [comment]
Where did you install the NEST synapse modules and could you show me the content of that directory?

**Comment by AaronSpieler** [comment]
I installed it using:
```
RUN cd e2l-cgp-snn/nest/us-sympy-synapse-module/ \
	&& mkdir build && cd build \
	&& cmake -Dwith-nest=/usr/local/bin/nest-config -Dwith-symengine=/usr/local ../ \
	&& make && make install
```

And when I check the container:
```
Step 28/28 : RUN ls /usr/local/lib/nest
 ---> Running in 21a7e312a4e7
HomeostaticSTDPmodule.so
libHomeostaticSTDPmodule.so
libmodels.so
libnest.so
libnestkernel.so
libnestutil.so
libprecise.so
librandom.so
libsli.so
libsli_readline.so
libstdp_sympy_synapse_module.so
libtopology.so
libus_sympy_synapse_module.so
libusrl_synapse_module.so
stdp_sympy_synapse_module.so
us_sympy_synapse_module.so
usrl_synapse_module.so
```

**Comment by mschmidt87** [comment]
I built your container and reproduced the error. I checked the contents of `/usr/local` and found that it contains only a static library `libsymengine.a`. The lib folder of symengine on my computer, however, contains a shared objects `libsymengine.so.0.3.0`. I think this is probably the source of the error, but I'm not sure why this happens.

**Comment by mschmidt87** [comment]
If you configure `symengine` with `-DBUILD_SHARED_LIBS=ON`, then the shared library is build instead of the static library, i.e. change your configuration of symengine (line 26) to
```
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/" ..
```
This solves the problem for me. Can you try this?

**Comment by AaronSpieler** [comment]
Yes! With your fix [Dockerfile.txt](https://github.com/Happy-Algorithms-League/e2l-cgp-snn/files/6266878/Dockerfile.txt) works and I can install all your modules.
 Thx so much for the quick fix!

**Comment by mschmidt87** [comment]
No worries, I am glad it worked. Not sure if symengine changed its default behavior recently, because I don't remember using this configuration option when building it. Anyway, I created #2 to add this instruction to our README, thanks for reporting this.

One more thing: would you mind if I use your Dockerfile and add it to the repo, @AaronSpieler ? I think this would be a useful addition to the repo.

**Comment by AaronSpieler** [comment]
Not at all, please go ahead. I haven't yet run all the experiments in the container to make sure that everything works yet, so maybe one should do that too before committing the Dockerfile. In any case, thx again!
